### ISSUE TITLE
search: permit unquoted queries

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#102]
Some search queries, like "P P --> W+ X" or "hep-ex/0102003", give a 500 error unless enclosed in quotation marks.

**Comment by alisonrclarke** [comment]
We can prevent the 500 error by catching the RequestError that comes back from Elasticsearch, and returning a friendly error message.

Knowing when to add quotation marks before sending to ES is trickier though, as quoting looks for an exact phrase match rather than a search on all words. Is it sufficient to look for the patterns given above and add quotation marks for only those patterns?

**Comment by alisonrclarke** [comment]
Have started work on branch [allow-unquoted-searches](/HEPData/hepdata/tree/allow-unquoted-searches). Gone down the route of only quoting query parts that look like reactions or dois to avoid changing the behaviour of other searches.
