### ISSUE TITLE
record: create submission preview utility

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#11]
To check how a submission looks even before submission.

**Comment by eamonnmag** [comment]
This is covered by the fact that files can be uploaded, reuploaded, etc. as part of the revision process, before fully 'publishing' the submission. Is this ok @GraemeWatt?

**Comment by GraemeWatt** [comment]
The point here was to have a "sandbox" so that people can upload data files and check for proper formatting even before the corresponding paper has been made public via arXiv submission.  This feature is available with the [current system] (http://hepdata.cedar.ac.uk/input) where input files can be uploaded for testing purposes even without a valid Inspire ID and password.

**Comment by eamonnmag** [comment]
Ok, great. Will do that then.

**Comment by eamonnmag** [comment]
![sandbox](https://cloud.githubusercontent.com/assets/282396/9355040/ba888e0e-4675-11e5-9ba7-e0ee55c2b720.gif)
