### ISSUE TITLE
Download complete record including (local) resource files

### ISSUE THREAD

**Issue by ghost** [HEPData/hepdata#110]
Hi,
as a coordinator I sometimes would like to make small changes to one of the yaml files (submission.yaml, usually). However, to upload my change I need a complete tarball that includes all resource files (except for external resources). Would it be possible to have the option to download a complete tarball with all required files? If you don't want to make this possible in general, could this power at least be granted to coordinators?
Thanks a lot!
Kilian

**Comment by GraemeWatt** [comment]
Good point.  This was actually done originally, where a `.zip` file was returned containing the `.yaml` files and all local resource files, but I changed the behaviour to pass the YAML files through the converter package so that the DOIs would be inserted and a `.tar.gz` file would be returned for consistency with the other formats (see #76).  But the side effect is that the local resource files are then not included, so maybe it would be better to revert to the original behaviour, perhaps converting from `.zip` to `.tar.gz`.  Another undesired side effect was that the `.tar.gz` file is cached and not updated when a new upload is made.  I'll look into fixing these problems.

**Comment by alisonrclarke** [comment]
@GraemeWatt I guess we need to decide:

- Whether we should be returning the converted YAML with DOIs or the original files
- .zip or .tar.gz (or both)
- Who should be able to download complete record (everyone, logged-in users, uploaders, or coordinators)

**Comment by GraemeWatt** [comment]
I think we should keep the existing YAML `.tar.gz` download with DOIs inserted (only `.yaml` files, no auxiliary files), but provide an additional endpoint/button giving access to the `.zip` file we already store on the disk (original `.yaml` files without DOIs inserted, plus auxiliary files).  Permissions should be the same as the main record, e.g. for finalised records, everyone should be able to access the `.zip` file, while permissions are restricted for records in progress.
