### ISSUE TITLE
Custom table names breaking several hyperlinks

### ISSUE THREAD

**Issue by ghost** [HEPData/hepdata#111]
For one recent record (https://www.hepdata.net/record/77719), we have tried to replace the default table names (Table 1, 2, 3, ...) by descriptive custom names, by changing the relevant lines in submission.yaml. This feature seems to be only partially supported at the moment; custom names seem to break the following functionality:
- Source files for an individual table cannot be downloaded ("Download all" still works)
- DOI links to individual tables seem to be broken / not registered successfully.
- Direct links to individual tables (those one can copy to the clipboard by clicking the copy button above each table) are broken
My first guess was that this may be due to spaces in the table names, which are not being escaped, but that alone doesn't solve the problems.

**Comment by GraemeWatt** [comment]
Yes, there are certain parts of the code that assume standard table names like "Table 1", "Table 2", "Table 3", etc.  I agree that more descriptive table names should be allowed and a few records have already been entered with non-standard table names, since these are not picked up by the validator package.  I'll try to look into making the necessary changes to the code, but to avoid problems in the meantime, it's simpler just to use the standard table names and move descriptive information from the table `name` to the `description`.  Issue #112 is likely also a side effect of using non-standard table names.

**Comment by ghost** [comment]
Loosely related and minor: I tried creating a direct link to one of the tables in the problematic record like this: https://www.hepdata.net/record/77719?version=1&table=1
The URL was accepted, but a table from a different record was displayed. (Note that I wrote "table=1" and not "table=Table1" which would have been correct.)
