### ISSUE TITLE
Failed sandbox uploads result in broken/fake entries

### ISSUE THREAD

**Issue by ghost** [HEPData/hepdata#114]
If a sandbox upload fails e.g. due to a parsing problem in submission.yaml, an entry is still added to the sandbox.  It is labelled as "None" and can be clicked, but although the URL looks like it should point to a record, one ends up in the sandbox again.

**Comment by GraemeWatt** [comment]
A failed Sandbox upload redirects to the upload form for that record where the user can upload again, with details of the failure now sent by email.  The list of records on the main Sandbox page is now labelled by the Sandbox record ID rather than "None" if there is no "comment" in the `submission.yaml` file.  Sandbox records without a valid upload can be deleted if they are no longer required.  I think this is acceptable behaviour, so I'll close this issue for now.
