### ISSUE TITLE
Problems with upload of large record (183 tables)

### ISSUE THREAD

**Issue by ghost** [HEPData/hepdata#115]
I'm trying to upload a large tarball (to the sandbox at the moment), but I'm always greeted with either a "502 Bad Gateway" page, or the HEPData "issues processing your request" page.

The record has 183 tables.  When I upload only the submission.yaml in a tarball, the overall structure of the record is created correctly.  As soon as I include the remaining yaml files, the upload fails after a while, and usually only a fraction of the tables can be seen in the record (typically a few dozen, in one instance only 18). I've tried with or without images files and got it to work without image files after several attempts, so the problem is not in the yaml files. I'll keep trying with the full tarball, but it would be good to understand where this limitation originates from and what to do about it.  I hope it's a simple matter of raising a timeout on the server.

**Comment by GraemeWatt** [comment]
This problem should be resolved now.  Sorry for the delay.  The server timeout has been increased from 90 seconds to 10 minutes.  In addition, we found a secondary problem that took a while to diagnose and work around, where some data files were returned as empty due to likely bugs affecting caching in the CERN EOS software.  Many thanks to @david-caro for helping to resolve these issues!
