### ISSUE TITLE
search: display latest items by last modified date rather than publication date.

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#125]

**Comment by salmele** [comment]
Is this really what users want? Imagine there are 5 measurement of the same things, with the most recent mostly superseding all others; this is what in principle I want to find as user. But, we discover a minor mistake in the spelling of the abstract of a older one, and fix it: we'd get this one on top, what is not desirable.

**Comment by eamonnmag** [comment]
This is what @GraemeWatt asked for. I agree with you though. As a user, I'd prefer the latest publications.

**Comment by salmele** [comment]
The issue is the implicit expectation of users for results to be ranked according to some relevance criterion. Latest publication date first is easy to understand. We had for a while analogous confusion in other Invenio-based systems where the default sorting was "date added" resulting in the phenomenon that users were presented random lists of results, without any connection with the scientific history of an idea, just because something old was discovered and added.

**Comment by eamonnmag** [comment]
:+1: @GraemeWatt, will it just be enough to sort by the publication date and to have the history of a submission available to see from the record page?

**Comment by GraemeWatt** [comment]
The "Latest Submissions" box at http://hepdata.net is meant to replace the Twitter feed (currently updated manually) embedded at http://hepdata.cedar.ac.uk .  This should mean "Latest **HEPData** submissions" whereas you currently show "Latest arXiv submissions which have HEPData", which is not the same thing.  Typically HEPData submissions are made several weeks/months after arXiv submission (although we hope that the gap can be reduced in future).  Suppose that two HEPData submissions are made immediately after arXiv submission, then these two records will appear at the top of the current "Latest Submissions" list regardless of the number of new HEPData submissions subsequently submitted for older papers.  You can see from our Twitter feed that indeed several HEPData submissions for older papers have been made following the two CMS papers that you currently show as "Latest Submissions".

A secondary issue is whether to show updates to HEPData submissions in the "Latest Submissions" box.  It might be beneficial to the user to know if data changes (rather than just typo corrections to metadata) and I was anticipating that code implementation might be simpler if both updates and new submissions appeared in the "Latest Submissions" box.  But indeed I do not usually publicise updates to records via the existing Twitter feed, so you might want to restrict the "Latest Submissions" box to only announce new submissions ("Version 1" but not "Version 2" etc.) if you prefer.

A separate issue is how to order the search results (e.g. clicking "Search" with a blank query).  In that case I agree that default ordering by publication date makes sense and should not be changed.  Indeed, the "Latest Submissions" box would be mostly redundant if it gave the same result as a blank search, so I think the behaviour should be different.  Having said that, an ability to order search results by HEPData submission date rather than arXiv submission date would still be useful (as is possible with Inspire, where the last added record is from 1954).  By the way, in the latest version of http://hepdata.net, the "Max results" and "Sort by" buttons seem to have no effect?

I tried to give more explanation in my original emails to Eamonn.  I also requested that the "Latest Submissions" box should be made scrollable, or a "Next 2" button should be added similar to the search facets, so that more records than the last two can be easily accessed.

**Comment by eamonnmag** [comment]
Hi @GraemeWatt, I'm sorting the sorting/max results thing. Not sure why that broke. Also, now emails are sent to reviewers when a new upload has been made, and uploaders are told of new messages by reviewers. On finalisation, an email is sent telling all participants in the submission that version x of record n is available at url.
