### ISSUE TITLE
Reviewer/Uploader email timing

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#127]
Currently the Uploader and Reviewer are sent emails at the same time, but the Reviewer can't do anything until the Uploader has uploaded their submission.  The Uploader may also need to upload several times before they are satisfied themselves that the record is correctly formatted and ready to be reviewed.  So it might be better to postpone the initial Reviewer invitation, then when the Uploader thinks that the record is ready to be reviewed they click a button saying something like "Notify Reviewer" that sends the invitation email to the Reviewer.  This workflow is closer to the existing HepData submission system.

**Comment by GraemeWatt** [comment]
The system should not send an email to the Reviewer for every upload.  As I suggested already, maybe postpone the initial Reviewer invitation until the Uploader clicks a button saying something like "Notify Reviewer", then the same invitation could contain a link to the record.  The Uploader can then click the "Notify Reviewer" at a later stage to send a further email to the Reviewer, i.e. the Uploader should be in charge of reviewer notifications.

**Comment by GraemeWatt** [comment]
Not sure that emails should be sent when every new comment is added (in any case, the subject should be corrected "upload" --> "comment").  My feeling is that after the first comment, the conversation will just take place by email rather than online, if comments are anyway sent by email.  On the other hand, both Reviewer and Uploader should probably be alerted to significant additions to the online conversation.  The Uploader could use the "Notify Reviewer" button, and maybe an analogous button "Notify Uploader" could be added for the Reviewer to alert the Uploader to significant comments that they have added, but the comments themselves would not be included in the emails.  This way if a comment was added for each table, only one notification could be sent rather than the Uploader receiving a separate email for each of the tables.

**Comment by GraemeWatt** [comment]
Maybe send an automatic email to the Coordinator when all tables have been marked as "passed review".

**Comment by GraemeWatt** [comment]
Can the paper titles be included in all emails?  Currently it is only done for the initial Uploader/Reviewer invitation.  This helps e.g. Coordinators who might be handling multiple papers simultaneously.

**Comment by GraemeWatt** [comment]
The subjects for the initial Uploader/Reviewer invitation should start with [HEPData] as for the other emails.

**Comment by eamonnmag** [comment]
@GraemeWatt - the danger here is that people don't click the buttons and submissions go stale. I don't think there will be that many emails in reality, will there? 
What I can do immediately is delay the reviewer email until the first upload is complete.

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#19
