### ISSUE TITLE
hepdata_records: preserve line breaks in the paper comments and table captions from the original YAML files

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#13]
_From @GraemeWatt on December 17, 2015 19:38_

Otherwise, e.g. the data abstract in https://hepdata.net/record/ins1203852 is much less readable than the original http://hepdata.cedar.ac.uk/view/ins1203852 .  I guess we just need to replace `\n` with `<br/>` in the HTML output.

Also, in converting the original single-file YAML format to the multiple-file YAML format, a lot of additional line breaks seem to be inserted.  This is probably because the `yaml.dump()` writer command wraps long lines of text by default and an argument `width` should be passed to preserve the original line breaks without wrapping long lines.

_Copied from original issue: HEPData/hepdata#152_

**Comment by GraemeWatt** [comment]
I don't think the second part of this issue was addressed yet, i.e. in migrating the original single-file YAML format ([example](http://hepdata.cedar.ac.uk/view/ins1203852/yaml)) to the multiple-file YAML format, the `comment` and `description` are written by default as quoted scalars rather than literal scalars when calling `yaml.dump()`, resulting in double-spacing wherever there is a newline character.  Adding the `width` option doesn't help, but I think a solution is to add the following code before calling `yaml.dump()` (slightly modified from http://stackoverflow.com/a/33300001):

```
def str_presenter(dumper, data):
    if "\n" in data:
        return dumper.represent_scalar('tag:yaml.org,2002:str', data, style='|')
    return dumper.represent_scalar('tag:yaml.org,2002:str', data)

yaml.add_representer(str, str_presenter)
```

This code will write all strings containing newline characters as literal blocks.  It will also be needed in other HEPData code that dumps YAML such as [hepdata-converter](https://github.com/HEPData/hepdata-converter), [hepdata-retriever](https://github.com/HEPData/hepdata-retriever), etc.
