### ISSUE TITLE
Table in HepData entry under validation never displays

### ISSUE THREAD

**Issue by richardhawkings** [HEPData/hepdata#135]
We are currently trying to validate the HepData record:

https://www.hepdata.net/record/77890

for the ATLAS paper Eur. Phys. J. C77 (2017) 804

There are 16 tables from the paper, all look fine apart from Table 13 (unlucky for some). When I (the submitted) or the ATLAS top convener reviewers click on Table 13, we get the animated particle collision 'waiting' icon, and the table itself never appears (even after waiting for 10 minutes). The other tables all appear, even though some take a few seconds. The format of the data is the same for all tables (and they are generated by a common script), so it is a bit strange that only one does not display. This issue currently blocks validation the HepData input for this paper.

I have verified that it happens with both Safari and Firefox web browsers, running on a Mac with OS 10.11.6.

thanks,
Richard Hawkings (CERN)

**Comment by GraemeWatt** [comment]
Thanks for the report.  The `data13.yaml` file was empty on the [CERN EOS](http://cern.ch/eos) disk.  I recovered the `data13.yaml` file from the `.zip` file and the table now loads in a browser.

We have had numerous similar problems with access to the data files stored on the [CERN EOS](http://cern.ch/eos) disk.  Many attempts have been made (e.g. 28577d851cabf69a1748c6a97eab81f3e41dc177, bb593c4fb515be27a09cb359064ca4cec9779895, 8c962138289939c11f68ede3d38662450bd0e7e8, 4bbf10cda8ac1e2248c50776014fa7a7f7e92b8d) to work around these problems with only partial success.  It has been suggested to port the HEPData code to use [XRootD](http://xrootd.org) directly rather than the [FUSE](http://eos-docs.web.cern.ch/eos-docs/configuration/fuse.html) client.  This was already done in https://github.com/inspirehep/inspire-next/commit/41f9cb0e275f5e2b211ebb9f6b9ed3d4ef912318 for [inspire-next](https://github.com/inspirehep/inspire-next) where similar problems were encountered.

I've closed this issue for now since it seems to be resolved for Table 13 of https://www.hepdata.net/record/77890, and I've opened a new issue #137 to solve the CERN EOS problems more generally.

**Comment by richardhawkings** [comment]
Many thanks - indeed this table is visible to me now. 
regards
Richard
