### ISSUE TITLE
Inspire record update feature missing?

### ISSUE THREAD

**Issue by alex-t-grecu** [HEPData/hepdata#152]
I could not find this feature in the portal interface when I log in as Coordinator. Could you please, clarify where to search for it or how to proceed to really update the Inspire metadata? Thank you in advance.

_Originally posted by @alex-t-grecu in https://github.com/HEPData/hepdata/issues/20#issuecomment-499038450_

**Comment by GraemeWatt** [comment]
This is still an open issue (#100).  The related issue #20 should not have been closed, since publication information for a specific record can be updated by a command run manually on the server by HEPData admin (me), but it is not yet an automatic procedure.  Let me know (by email) if there are any finalised records for which you wish to update publication information.  This procedure is described in the third paragraph of the [Introduction](https://hepdata-submission.readthedocs.io/en/latest/introduction.html) of the submission documentation.

I still don't see that an automatic procedure for updating publication information has a high priority, but I started to think about a possible implementation.  My idea is to automatically run an [INSPIRE search](https://inspirehep.net/search?p=035__9:hepdata%20and%20du%20yesterday) once per day to find INSPIRE records with HEPData that were modified the previous day (the "last modified" date that appears in the bottom-left of an INSPIRE detailed record page).  Then for each of these INSPIRE records, I can compare the publication information with that stored in the HEPData record and update the latter if there is any difference.  After this code is implemented for future automatic updates, I would also loop over *all* HEPData records to check for any updates to the publication information stored in INSPIRE.

**Comment by alex-t-grecu** [comment]
Since there are obviously some security issues that it's best to be avoided, I wonder whether it wouldn't be easier to implement some feature (available only to coordinators since after all it's their responsibility) by which records are flagged if they need such an intervention. This way you'd definitely reduce the interogations to Inspire. Moreover, when experiments release papers that are in the process of journal reviewing (but they are or arXiv already) it would be useful to be able to set a flag so that this update operation is automatic. Anyway lauching interogations to Inspire would be helpful to be able to ping coordinators about updating records in case an erratum gets published.

**Comment by alex-t-grecu** [comment]
As a test I tried "marking" some records with missing publication info by sending messages from the interface. Please, let me know if this method is helpful for you. Anyway, it would be useful to have just some buttons to specify quickly such common issues with records.
