### ISSUE TITLE
deps: cleaning requirements.txt

### ISSUE THREAD

**Issue by Sinclert** [HEPData/hepdata#186]
When trying to keep track of the dependencies that this application relies on, it is hard to figure out them at a quick glance due to the enormous list present in the `requirements.txt` file as it comes from running `pip freeze` 2 years ago.

In addition, some of the dependencies are **indirect** to the application, meaning the the application itself does not use them, they are only used by some particular dependency. Those "_indirect_" references should be removed from the `requirements.txt` file, **as it is the responsibility of the "_direct_" dependency to decide  its relationship to them**.

To tackle this issue, I have started cleaning up the [requirements.txt](https://github.com/Sinclert/hepdata/blob/requirements-list/requirements.txt) file in [this branch](https://github.com/Sinclert/hepdata/tree/requirements-list).

I am programmatically searching the whole application (after having installed all packages in a virtual env.) in order to categorize the dependencies into:
- **Directly used** ✅ 
- **Indirectly used** ⚠️ 
- **Not used** (random packages that may have been there when running `pip freeze`) ❌

The final goal would be to **remove** all dependencies but those that are **directly used**.

Feel free to state any concerns / regards about this process.

**Comment by GraemeWatt** [comment]
I agree this sounds like a good idea.  Until two years ago, the Travis CI build frequently failed when installing new incompatible versions of packages, particularly when Invenio v3 was still in the early stages of development.  I pinned the package versions to the results of `pip freeze` as a temporary (but drastic!) measure in 2018 when Invenio v3.0.0rc1 and v1.0.0 of the component packages broke the Travis CI build (see HEPData/hepdata#138), since I wanted to mirror the production environment at CERN.  I agree that removing all dependencies other than those **directly used** is a worthwhile goal.  I suggest that we postpone completing this work until after the HEPData code is migrated from Python 2 to Python 3 (see HEPData/hepdata#158), since the dependencies will change (see [requirements.txt](https://github.com/DurhamARC/hepdata/blob/update/python3-compatibility/requirements.txt) in [this branch](https://github.com/DurhamARC/hepdata/tree/update/python3-compatibility)).  We also need to set up new VMs at CERN with a Python 3 environment, including a `qa` server for testing.  The Travis CI build should be as close as possible to the production (or `qa`) environment.

**Comment by Sinclert** [comment]
I have created a [PR](https://github.com/HEPData/hepdata/pull/187) to address this issue.

The PR includes an initial cleaning of the requirements. However, it has failed the CI testing as there are deeper dependencies problems that what can be seen on surface.

A complete diagnostic of the problems has been done in comments:
- [Problem 1: urllib3](https://github.com/HEPData/hepdata/pull/187#issuecomment-594132423).
- [Problem 2: oauthlib](https://github.com/HEPData/hepdata/pull/187#issuecomment-594153261).
- [Problem 3: click](https://github.com/HEPData/hepdata/pull/187#issuecomment-594167292).

Within the comments, I suggest solutions to the problems.

Please, let me know which approaches you think are best, so I can include them into the PR.

**Comment by Sinclert** [comment]
The [PR](https://github.com/HEPData/hepdata/pull/187) is now passing all the tests ✅ 

In order to have this _issue_ as a clean summary of changes, here are the last steps to make the [PR](https://github.com/HEPData/hepdata/pull/187) successful:

- [Problem 4: pre-installed packages in the Travis runners](https://github.com/HEPData/hepdata/pull/187#issuecomment-598853996) (incompatibility over `six`).
- Problem 5: hidden `invenio-theme` dependency (now added back).
