### ISSUE TITLE
model: remove participants from HEPSubmission object

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#230]
There is a `SubmissionParticipant` object defined in `hepdata/modules/permissions/models.py`.  The `HEPSubmission` object in `hepdata/modules/submission/models.py` also defines a `participants` column which links to the `SubmissionParticipant` object:
https://github.com/HEPData/hepdata/blob/2f6526dd2b33bf0f5700bd206dcfb97d2bc81695/hepdata/modules/submission/models.py#L32-L38
https://github.com/HEPData/hepdata/blob/2f6526dd2b33bf0f5700bd206dcfb97d2bc81695/hepdata/modules/submission/models.py#L90-L92
The `SubmissionParticipant` is independent of a version, but `HEPSubmission` depends on a version and the `participants` are not copied when creating a new version:
https://github.com/HEPData/hepdata/blob/2f6526dd2b33bf0f5700bd206dcfb97d2bc81695/hepdata/modules/records/api.py#L355-L359
The code queries both the `SubmissionParticipant` table directly and the `participants` column of the `HEPSubmission` table (for example, for the Dashboard display) leading to some inconsistencies for versions of 2 or greater.  It would be simpler to only use the `SubmissionParticipant` table throughout the code and remove the `participants` column of the `HEPSubmission` table.  After the code is modified to remove use of the `participants` column, perhaps the DB cleanup could be done at the same time as #139 (?).

**Comment by alisonrclarke** [comment]
I think this can probably be kept separate from #139 - dropping the `submission_participant_link` table and the `participants` column should leave the DB in a sensible state.

**Comment by GraemeWatt** [comment]
The issue of the submission participants not being copied to the new version when "Revise Submission" is clicked was raised by Frank Geurts (Coordinator for STAR).  I'll bump the priority.  This issue should be addressed with #231.

**Comment by alisonrclarke** [comment]
Just looking into this again. Using the `submission_participant_link` table is the [recommended way to define a many-to-many relationship](https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html#many-to-many) (multiple `hepsubmission` records for different versions map to multiple participant records). I think the issue we have is that the `SubmissionParticipant` also includes the `publication_recid` field which causes duplication of data, so in many places we rely on that rather than the link table, hence the confusion and some missed updates. 

I think the 'right' way to fix this would be to add in any missing entries to `submission_participant_link` then remove the `publication_recid` field from the `SubmissionParticipant` table (and fix the code to use the link table throughout). That should ensure database integrity, but it may be more work than removing the link column as I think more of the code makes use of the `SubmissionParticipant.publication_recid` than the `HEPSubmission.participants` field.

**Comment by GraemeWatt** [comment]
Yes, I think it would be simpler to only use the `SubmissionParticipant` table throughout the code and remove the `participants` column of the `HEPSubmission` table, even if this is not necessarily the best way to define a relationship between database tables.
