### ISSUE TITLE
records: modify get_record_contents to get record from DB if not finalised

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#244]
The function [get_record_contents](https://github.com/HEPData/hepdata/blob/9d547c27e734f35ed7a8af152e78a847f6c1a2f8/hepdata/modules/records/utils/common.py#L207-L221) is called for the Dashboard display and for normal record display.  It first tries to get the record from Elasticsearch using [get_record](https://github.com/HEPData/hepdata/blob/9d547c27e734f35ed7a8af152e78a847f6c1a2f8/hepdata/ext/elasticsearch/api.py#L209-L222), falling back to the database using [get_record_by_id](https://github.com/HEPData/hepdata/blob/1e2171ee39c16e45e82147d24284558aa18f87d5/hepdata/modules/records/utils/common.py#L224-L234).  We recently received notification from CERN IT that there are regular 404 errors from the Elasticsearch instance.  This is because unfinished or Sandbox records are not available in the Elasticsearch index, therefore the HEPData code should not try to access records there.  A check should be made for `overall_status=finished` of the HEPSubmission object before attempting to access a record from the Elasticsearch index.  Alternatively, the `get_record_contents` could be modified to always use `get_record_by_id` (the database) rather than `get_record` (Elasticsearch) if the information is the same.

**Comment by alisonrclarke** [comment]
Most records are indexed, so using ES for speed where we can is probably a good plan. Going to take a 2-pronged approach:

 * For cases where we have a submission object when calling `get_record_contents`, modify  `get_record_contents` to accept a status argument and check for `overall_status=finished` before searching ES. This should reduce unnecessary ES calls where we know the record is not finalised and has not been indexed.
 * Modify `get_record` to use a search query by id rather than directly getting the document, so that ES returns an empty result set rather than a 404.
