### ISSUE TITLE
migration: copy individual files linked from parent files to resource area on hepdata.net

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#27]
_From @GraemeWatt on December 17, 2015 18:17_

Clicking "Link to the SLHA files" in the Additional Resources for https://hepdata.net/record/ins1127601 gives links to individual .slha files stored on hepdata.cedar.ac.uk rather than hepdata.net.  I guess we should eventually copy these files across, i.e. everything in the web directory http://hepdata.cedar.ac.uk/resource/9719717 and replace hard-coded links to files in that directory.  Similarly for other records where files are linked from something like "insert.html" or "index.shtml".

_Copied from original issue: HEPData/hepdata#141_

**Comment by eamonnmag** [comment]
I'm not sure what to do here. In some respects, it may be better to list all resources directly in the YAML export as opposed to just this link. Having to support this page as an index, and convert all the HTML files to use correct links etc. is not going to be nice, but I'll give it a try. Now, this shows. But each of the Y links is still going back to cedar.hepdata. So, I need to pull the contents of these resource directories and create HEPData resource objects for them (in the db). Then, I need to go through the HTML files and replace all cedar.hepdata... links with hepdata/resource/<resource_id> links. 

![screen shot 2016-01-13 at 14 05 09](https://cloud.githubusercontent.com/assets/282396/12295104/20a6a1ce-b9ff-11e5-8e9c-641cfd34972c.png)

**Comment by eamonnmag** [comment]
We need to determine what to do here. Having to go and harvest all the files linked to by this HTML file is not going to be efficient.

**Comment by GraemeWatt** [comment]
For this example, all the SLHA files are included in the gzipped tar file, and (in my opinion) it's not essential to preserve the HTML table of "y" links to individual SLHA files.  So I've simplified the `additional_resources` for this record so that it can be easily migrated:

```
  - {location: '/resource/9719717/3LHEPdata_SLHA.tar.gz', description: 'gzipped tar file of all the SLHA files'}
```

Alternatively, and necessary for more complicated examples like http://hepdata.cedar.ac.uk/view/ins1125961 containing http://hepdata.cedar.ac.uk/resource/9703683/insert.html, where each of the "select" links is a separate HTML file, and the SLHA links each lead to HTML tables of "y" links to individual SLHA files, we could edit all the HTML files so that links are relative rather than absolute (removing reference to hepdata.cedar.ac.uk), then pack the `insert.html` file and all linked files into a single `.tar.gz` file given in the `additional_resources`.  Then a user would need to download and unpack the `.tar.gz` and view the local `insert.html` file in a browser.  This method is simple, results in no loss of information, and requires no changes to the migration code.  However, I'll need to go through each of the affected records individually to make the changes, which will take some time.  I guess it's not urgent, though, if we can do a bulk migration now, and then remigrate the affected records individually at a later stage after the `additional_resources` have been simplified.

**Comment by GraemeWatt** [comment]
I finally got around to simplifying the `additional_resources` and remigrating each of the affected records:

- [x] https://hepdata.net/record/ins1127601
- [x] https://hepdata.net/record/ins1125961
- [x] https://hepdata.net/record/ins1304459
- [x] https://hepdata.net/record/ins1380183
- [x] https://hepdata.net/record/ins1247060
- [x] https://hepdata.net/record/ins1228693
- [x] https://hepdata.net/record/ins1241574
- [x] https://hepdata.net/record/ins1221252
- [x] https://hepdata.net/record/ins1262319
- [x] https://hepdata.net/record/ins1258398
- [x] https://hepdata.net/record/ins1289225
- [x] https://hepdata.net/record/ins1304288
- [x] https://hepdata.net/record/ins1286113
- [x] https://hepdata.net/record/ins1180197
- [x] https://hepdata.net/record/ins1204284
- [x] https://hepdata.net/record/ins1282905
- [x] https://hepdata.net/record/ins1286761
- [x] https://hepdata.net/record/ins1297226
- [x] https://hepdata.net/record/ins1286444
- [x] https://hepdata.net/record/ins1298722
- [x] https://hepdata.net/record/ins889431
- [x] https://hepdata.net/record/ins890749
- [x] https://hepdata.net/record/ins916840
- [x] https://hepdata.net/record/ins930002
- [x] https://hepdata.net/record/ins1112263
- [x] https://hepdata.net/record/ins1190891
- [x] https://hepdata.net/record/ins1198427
- [x] https://hepdata.net/record/ins879315
- [x] https://hepdata.net/record/ins925932
- [x] https://hepdata.net/record/ins939504
- [x] https://hepdata.net/record/ins1082936
- [x] https://hepdata.net/record/ins1083318
- [x] https://hepdata.net/record/ins1094564
- [x] https://hepdata.net/record/ins1094860
- [x] https://hepdata.net/record/ins1117704
- [x] https://hepdata.net/record/ins1120512
- [x] https://hepdata.net/record/ins1186556
