### ISSUE TITLE
HEPData filters tables with and without spaces - but provides wrong download links

### ISSUE THREAD

**Issue by kratsg** [HEPData/hepdata#334]
This is a UI bug that was not immediately obvious to me that it was a problem.

Use this record as an example: https://www.hepdata.net/record/89413

1. scroll through Table 1 and pick a contour like [`expected exclusion contour smuon-pair production`](https://www.hepdata.net/record/89413?version=1&table=Exclusioncontour(obs)9)
2. On this page, confirm we're on the right contour selected
  ![Screen Shot 2021-04-22 at 2 43 38 PM](https://user-images.githubusercontent.com/761483/115769100-27db8400-a379-11eb-97c7-c5d1df18d1d5.png)
3. Note that the url is `https://www.hepdata.net/record/89413?version=1&table=Exclusioncontour(obs)9` where there's no spaces in the name of the table, but it seems fine. Click the download to download the `ROOT` version of this contour which links to https://www.hepdata.net/download/table/ins1750597/Exclusioncontour(obs)9/1/root
4. Hit converter error `A data submission with Inspire ID 1750597, version 1 and table name 'Exclusioncontour(obs)9' does not exist`
  ![Screen Shot 2021-04-22 at 2 44 41 PM](https://user-images.githubusercontent.com/761483/115769222-4fcae780-a379-11eb-8b6b-9359b61a5215.png)
5. Go back, physically click on the `Exclusion contour (obs) 9` on the left, which reloads the page on the right -- and click the download link again which links to: https://www.hepdata.net/download/table/ins1750597/Exclusion%20contour%20(obs)%209/1/root

There seems to be a problem with how the download links are generated.

**Comment by GraemeWatt** [comment]
Thanks for the report.  I'm not sure if this is really a bug, rather than misuse of links with table names.  You should always specify the original spaces in the table names, with the one exception of simple table names matching the regex `^Table \d+$` where the space is optional.  Otherwise, HEPData does not support links containing table names without the original spaces.

How did you get to https://www.hepdata.net/record/89413?version=1&table=Exclusioncontour(obs)9?  Selecting tables by clicking from https://www.hepdata.net/record/89413 does not change the URL.  You can get a link to a specific table by clicking the clipboard icon next to the URL above each table.  That link will always contain the original spaces in the table name (apart from `^Table \d+$` where the space is removed).  You can find the download links for each table in the JSON format of the record (https://www.hepdata.net/record/89413?format=json) as well as by clicking the download icon above each table.  In the JSON format we define a `processed_name` (with spaces removed) as well as the original table `name`.  The reason is that the JavaScript table selection uses HTML class attributes that cannot have spaces.  This explains why the table selection still works if spaces are removed from the table name, even if it breaks the download links.

Please close this issue if you agree there is no bug, or specify what you would like to be changed.  I'm reluctant to modify the HEPData code to support links containing table names with or without spaces, as this increases the complexity of the code and would likely introduce bugs.

**Comment by GraemeWatt** [comment]
Sorry, I missed your first point 1. that you clicked the link from the first [Table 1](https://www.hepdata.net/record/ins1750597?version=1&table=Table1).  These links were encoded (without spaces) in the YAML submission by the ATLAS uploaders.  The links should have been encoded with spaces and could be corrected in a new "Version 2" of the submission.  On the other hand, I see your point that it is not obvious that the download links would be broken if the table selection works without spaces, so it does look like a bug.  I'll leave this issue open and we'll investigate if the download links can be fixed if spaces are omitted in the table name passed in the URL.  Thanks again for your report!

**Comment by kratsg** [comment]
No problem, thanks!

**Comment by GraemeWatt** [comment]
@kratsg, we've just deployed a fix for this issue.  Links are now given including spaces, but they now also work if the spaces are omitted.  We've also removed the special treatment of table names matching `^Table \d+$`.  Many thanks once more for your report and helping to improve the HEPData service!
