### ISSUE TITLE
submission: use new FullSubmissionValidator class from hepdata-validator

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#388]
After HEPData/hepdata-validator#32 is merged and a new release 0.3.0 of the `hepdata-validator` package is made, the [`process_submission_directory`](https://github.com/HEPData/hepdata/blob/e22006ed9fbdcddddea221df7551c816fcfba231/hepdata/modules/records/utils/submission.py#L411) function should be refactored to use the new `FullSubmissionValidator` class.  A complete submission should pass validation before creating new `DataSubmission` objects.  Checks that are now made in the `FullSubmissionValidator` class can then be removed from the `process_submission_directory` function.

**Comment by alisonrclarke** [comment]
This would also address #274 as that is now included in HEPData/hepdata-validator#32.

It may be that further changes are needed to hepdata-validator to ensure the functionality of `FullSubmissionValidator` is exactly the same as that in `process_submission_directory`, as it is currently based on the [`check.py` script](https://raw.githubusercontent.com/HEPData/hepdata-submission/master/scripts/check.py) rather than on `process_submission_directory`.
