### ISSUE TITLE
badges: support badges on records with rivet analysis for example

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#47]

**Comment by GraemeWatt** [comment]
Also add the Rivet badge to the actual record, not just to the search results.  (It would be good if the code was flexible enough that badges could easily be added for other theoretical frameworks, see #58.)

At the moment, a record with a Rivet analysis is identified from the presence of a link with "hepforge" in the additional resources.  This is not ideal for future submissions, since the Rivet analysis might appear some time after the corresponding HEPData record.  Links containing "hepforge" are not restricted to Rivet analyses and HepForge is used for many other projects besides Rivet (maybe look for the string "rivet.hepforge.org/analyses" in the link, not just "hepforge").

Instead a Celery task should be created which runs (say) once a day and updates the list of HEPData records that have a Rivet analysis from a [JSON file](http://rivet.hepforge.org/list_of_analyses.json).  The Rivet badges could be linked to e.g. "http://rivet.hepforge.org/analyses#ALEPH_1991_S2435284" where the part after the # is the analysis name given in the JSON file.  A few papers have more than one Rivet analysis (given as a list in the JSON file), so I guess we should show multiple Rivet badges in these cases, each one linked with the corresponding Rivet analysis name.

**Comment by eamonnmag** [comment]
Do you have any examples with FastNLO etc? Would be useful to check for the general applicability of my solution.

**Comment by GraemeWatt** [comment]
Click the left sidebar at http://fastnlo.hepforge.org/scenarios/, e.g. list of LHC papers at http://fastnlo.hepforge.org/scenarios/tables-lhc.html.  The linked HepData records contain local copies of the fastNLO tables, so you could add a fastNLO badge if the `description` of the `additional_resources` for the publication contains the word `fastNLO`.

But as with the Rivet analyses, new fastNLO tables might appear some time after the corresponding HEPData record, so it would be better to ask the fastNLO authors to provide a JSON file (e.g. http://fastnlo.hepforge.org/list_of_analyses.json) in the same format as for the list of Rivet analyses.  Again, there can be more than one fastNLO table (e.g. "fnl2732numa_I1230937" and "fnl2732dena_I1230937") for a given Inspire ID (e.g. "1230937").

I think that other theoretical frameworks will be similar, i.e. in future we just ask the authors to provide an up-to-date JSON file mapping Inspire IDs of the publication to (possibly multiple) analysis names.  Sometimes the badge can be linked to a URL for each analysis (as for Rivet).  Some changes to the code will probably be needed to add badges for a new theoretical framework, but hopefully not too many if you can generalise the code at this stage.

**Comment by GraemeWatt** [comment]
Other examples of theoretical frameworks that provide files corresponding to experimental papers:
- [APPLgrid](https://applgrid.hepforge.org/downloads.htm)
- [MadAnalysis5](http://madanalysis.irmp.ucl.ac.be/wiki/PublicAnalysisDatabase)
- [xFitter](http://xfitter.hepforge.org/data.html)
