### ISSUE TITLE
Download of hepdata entry is broken with runtime error

### ISSUE THREAD

**Issue by kratsg** [HEPData/hepdata#509]
One of the older submissions from 2016 or so (used to work in the past, now currently broken) -- https://www.hepdata.net/record/ins1634607 -- when downloading any information. Do you know how we can download the files?

**Comment by GraemeWatt** [comment]
Thanks for pointing this out.  The "Download All" → "YAML with resource files" link is working, but other formats are broken.  The reason is that the three resource files are specified in the **last** YAML document of the `submission.yaml` file:
```yaml
additional_resources: 
- {description: Code snippet with the implementation of the analysis selection at truth-level, as used to produce the acceptance numbers, location: ThreeBjets2016.cxx}
- {description: SLHA file for benchmark Gtt signal, location: param_card.SM.GG.ttn1.dat}
- {description: SLHA file for benchmark Gbb signal, location: param_card.SM.GG.bbn1.dat}
```
but our code assumes that this information is given in the **first** YAML document of the `submission.yaml` file.  The validator should now catch this mistake upon upload, but it must have been permitted in 2018.  I'll try to manually edit the `submission.yaml` file stored on disk to move the last YAML document to the start of the file, then hopefully the converter will work afterwards.

**Comment by GraemeWatt** [comment]
Now fixed for all four versions of https://www.hepdata.net/record/ins1634607 .  Thanks again for the report.

**Comment by kratsg** [comment]
Hi @GraemeWatt doesn't seem fixed for me. Am I hitting a cache'd page? For example https://www.hepdata.net/download/table/ins1634607/Table%201/4/root is giving me an html page.

Error

`
RuntimeError: Submission file (/tmp/tmp7lsnsuxp/data1/submission.yaml) did not pass validation: /tmp/tmp7lsnsuxp/data1/submission.yaml: 'name' is a required property in {'additional_resources': [{'description': 'Code snippet with the implementation of the analysis selection at truth-level', 'as used to produce the acceptance numbers': None, 'location': 'ThreeBjets2016.cxx'}, {'description': 'SLHA file for benchmark Gtt signal', 'location': 'param_card.SM.GG.ttn1.dat'}, {'description': 'SLHA file for benchmark Gbb signal', 'location': 'param_card.SM.GG.bbn1.dat'}]} // Werkzeug Debugger
`

**Comment by GraemeWatt** [comment]
Works for me.  I think it's a local caching problem.  Try clearing your browser cache.

**Comment by kratsg** [comment]
Works for me now! Thanks again!
