### ISSUE TITLE
invenio-accounts: diagnose and update invenio-accounts to v2.0.0

### ISSUE THREAD

**Issue by ItIsJordan** [HEPData/hepdata#539]
After updating to invenio-accounts v2.0.0 and attempting to run **clean_assets.sh** or **initialise_db.sh**, the error **"sqlalchemy.exc.ArgumentError: Error creating backref 'external_identifiers' on relationship 'UserIdentity.user': property of that name exists on mapper 'mapped class User->accounts_user'"** occurs. The _invenio-userprofiles (to 2.x)_, _invenio-oauthclient (to 2.x)_ and _Flask-Login (to 0.6.x)_ package updates require also require _invenio-accounts_ updated to >2.0.0.

**Comment by GraemeWatt** [comment]
The [changes](https://invenio-accounts.readthedocs.io/en/latest/changes.html) for v2.0.0 indicate changes to the database model.  So database migration using [Alembic](https://alembic.sqlalchemy.org/en/latest/) is probably needed, i.e. run `hepdata alembic upgrade` to execute the appropriate migration commands from [invenio-accounts](https://github.com/inveniosoftware/invenio-accounts/tree/master/invenio_accounts/alembic).  Alternatively, you could use `dropdb` for `hepdata` and `hepdata_test` and [create them again](https://hepdata.readthedocs.io/en/latest/installation.html#id5), but obviously we can't do this for the production database, so we need to test that the migration works.

**Comment by GraemeWatt** [comment]
The error arises because `UserIdentity` from `invenio-oauthclient` was moved to `invenio-accounts` in the v2.0.0 versions (see [changes](https://invenio-accounts.readthedocs.io/en/latest/changes.html)), so both packages need to be upgraded together.  Here is a list of changes needed:

- [x] Edit `requirements.txt` to install `Flask-Login==0.6.2`, `invenio-accounts==2.0.0`, `invenio-app==1.3.4`, `invenio-oauthclient==2.0.1` and `invenio-userprofiles==2.0.3`.
- [x] Run `pip install -e ".[all]" --upgrade -r requirements.txt` and `./scripts/clean_assets.sh`.
- [x] Run `hepdata alembic upgrade` to migrate relevant tables of the database to the new Invenio versions.  It might be a good idea to first dump the database (`pg_dump`) so that it can be later restored (`pg_restore`) if necessary.
- [x] Remove `SECURITY_PASSWORD_SALT = "CHANGE_ME"` from `config.py` and add `SECURITY_PASSWORD_SINGLE_HASH = True` to preserve the password-hashing behaviour of the previous `invenio-accounts`.
- [x] Make these changes to the Dashboard code: 
```python
--- a/hepdata/modules/dashboard/views.py
+++ b/hepdata/modules/dashboard/views.py
@@ -75,9 +75,9 @@ def dashboard():
         user_to_display = get_dashboard_current_user(current_user)
 
     if user_to_display == current_user:
-        user_profile = current_userprofile.query.filter_by(user_id=user_to_display.get_id()).first()
+        user_profile = current_userprofile
     else:
-        user_profile = UserProfile.query.filter_by(user_id=user_to_display.get_id()).first()
+        user_profile = UserProfile.get_by_userid(user_to_display.get_id())
 
 
     ctx = {'user_is_admin': has_role(user_to_display, 'admin'),
@@ -244,7 +244,7 @@ def submissions():
         user = get_dashboard_current_user(current_user)
 
     if has_role(user, 'admin') or has_role(user, 'coordinator'):
-        user_profile = UserProfile.query.filter_by(user_id=user.get_id()).first()
+        user_profile = UserProfile.get_by_userid(user.get_id())
         url_for_params = { 'view_as_user': user.id } if user != current_user else {}
         dashboard_url = url_for('hep_dashboard.dashboard', **url_for_params)
```
- [x] In `tests/dashboard_test.py` the global `dashboardTestMockObjects` dict needs to be defined inside the app context.  I got the tests to pass by duplicating the code inside each function, but there is probably a smarter way to do it without duplication.
- [x] Make these changes to `tests/e2e/test_accounts.py`:
```python
--- a/tests/e2e/test_accounts.py
+++ b/tests/e2e/test_accounts.py
@@ -26,7 +26,7 @@ import flask
 
 from .conftest import e2e_assert, e2e_assert_url
 from invenio_accounts import testutils
-from invenio_accounts.models import User
+from invenio_accounts.models import User, LoginInformation
 from invenio_db import db
 from itsdangerous import URLSafeTimedSerializer
 from flask_security import utils
@@ -148,5 +148,7 @@ def test_user_registration_and_login(live_server, env_browser):
 
     # Delete the newly created account
     user = User.query.filter_by(email=user_email).first()
+    login_information = LoginInformation.query.filter_by(user_id=user.id).first()
     db.session.delete(user)
+    db.session.delete(login_information)
     db.session.commit()
```
After these changes, all tests should pass, including the E2E tests.
