### ISSUE TITLE
theme: add a better display for the list of presentations

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#793]
As the list of presentations keeps growing at https://www.hepdata.net/about#presentations a better display format should be implemented.  For example, only display the most recent two (say) with a button saying "More..." that brings up a widget where the user can scroll through the complete list of presentations.

**Comment by ItIsJordan** [comment]
I have made some changes to this list in the "about-display-list" branch to add a button toggling display of all presentation entries on the about page (with  at least 3 shown by default, at all times).

NOTE; Since writing this, we discussed making this widget always scrollable, with no button, setting a max-height so results do not extend the length of the webpage.
