### ISSUE TITLE
Having problem to update new data

### ISSUE THREAD

**Issue by LouisHelary** [HEPData/hepdata#85]
Hi,

I'm having problems to upload a new dataset. Everytime I'm connecting to my sandbox to try uploading it I end up with this message: https://www.hepdata.net/static/img/errors/500.svg

Is the server really experiencing some problem, or did I do something wrong?

Best,
Louis

**Comment by GraemeWatt** [comment]
Hi Louis,

It usually means there is a problem with the upload format.  A known issue, which I will fix soon, is that if you download the YAML format of an existing submission and try to upload it, the lines giving the data DOIs currently have `!!python/unicode` tags which causes the server to reject the upload.  Remove these lines from the `submission.yaml` file and the upload will be accepted.  Please also check that your upload files are valid YAML: there are various online YAML validators you can find with Google where you can check by pasting your text into a web form.  Otherwise, please send me your upload by email to `info@hepdata.net` and I will try to diagnose the problem and improve the upload code if necessary.

Thanks,
Graeme Watt (HEPData)

**Comment by LouisHelary** [comment]
Hi Graeme,

Thanks for your quick reply, however it seems that now anytime I'm trying to access my sandbox I end up directly to the error message, I have effectively uploaded the data files only once to it. I think the same goes for the actual submission I was trying to make.

Best,
Louis

**Comment by GraemeWatt** [comment]
The error message for a failed submission will be shown on `https://www.hepdata.net/record/sandbox/consume`.  Go to `https://www.hepdata.net/record/sandbox` and you should be able to upload again.  Try reloading the page: maybe the page with the error is just stuck in your browser cache.

**Comment by LouisHelary** [comment]
Well that's what I originally thought, so I went to try to reupload with Safari instead of firefox and I still end up with the same error message. If I try to go here:
https://www.hepdata.net/record/sandbox/consume

I get:
Method Not Allowed

The method is not allowed for the requested URL.

**Comment by GraemeWatt** [comment]
OK, that URL (https://www.hepdata.net/record/sandbox/consume) is not meant to be public, so it *should* give an error message.  So you always get a 500 error from https://www.hepdata.net/record/sandbox?  What about https://www.hepdata.net/dashboard/?

It might be a more general authentication problem.  Are you using a CERN email address to log in with a password you provided on the HEPData site?  I've found some problems with this method.  Try logging out then selecting "Log in with CERN" from https://www.hepdata.net/login/ rather than entering your email address and password.

**Comment by LouisHelary** [comment]
The Dashboard looks to be working indeed. Do you think I can do the test to upload the data (and see whether my files are working), directly on the submission page, or it is better to do these tests on the sandbox?

And yes, I'm login through the CERN address using the Log in with CERN method.

**Comment by GraemeWatt** [comment]
So I found your upload on the server and I think I understand the problem, which was caused by non-ASCII characters in the `comment` of your `submission.yaml` file.  Find them with:
`grep --color='auto' -P -n '[^[:ascii:]]' submission.yaml`
I unloaded your submission from the database, so please check if your Sandbox can be accessed now.  In future, I'll try to make the code more robust against uploads like this, but please remove any non-ASCII characters for now.  Thanks for the feedback!

**Comment by LouisHelary** [comment]
Hi Graeme,

Sorry for the slow reply, so I did has instructed, but the tarball still does not compile (by the way can you also accept the .tgz upload?), isn't it possible from the sandbox to understand what goes wrong instead of a single message that it doesn't work?

Best,

Louis

**Comment by GraemeWatt** [comment]
I found your latest upload on the server: it fails because the last uncommented line of `submission.yaml` is `---`, which defines a new (empty) YAML document and causes our code to give an exception.  Comment out the final `---` and the `submission.yaml` file is valid.

There's another mistake in `data1.yaml` where `value: ` is missing for the `RE` qualifier of the second dependent variable.  However, this mistake is caught by our validator package and an error message is printed out on the upload form.

`.tgz` files are not currently accepted (only `.tar.gz`), although I guess we could modify the code to allow them.  Attempting to upload a `.tgz` file currently gives an error message.

In general, the upload form should print out an error message for a failed submission that gives information on the invalid line of the input file.  However, I agree that I need to catch the exceptions caused by empty YAML documents in `submission.yaml` and the presence of non-ASCII characters (you can use LaTeX encoding with ASCII characters, which will be rendered using MathJax, rather than Unicode characters).

**Comment by LouisHelary** [comment]
Hi Graeme,

Thanks for your support! It seems that I have always had the error message, whatever I did uploaded to the site, but at least now the entry seems to be accessible.

Best,

Louis
