### ISSUE TITLE
Data encoding: Limit number of e-mail messages from reviewer comments

### ISSUE THREAD

**Issue by alex-t-grecu** [HEPData/hepdata#86]
Dear developers,
In order to reduce the number of e-mail messages received by an encoder while a submitted, preliminar record is reviewed, I would propose to check and send an e-mail every 30 minutes for each preliminar record informing the encoder of the comments and suggestions filled-in by the reviewer. Or at least offer the coordinators a choice to select such a behaviour policy for records under their responsibility.
Thanks,
Alex

**Comment by GraemeWatt** [comment]
Yes, it's maybe better not to send an email every time the "Send Feedback" button is clicked on each table.  There could be a "Notify Uploader" button on the record that allows a Reviewer to send an email to the Uploader with the review status of each table and associated comments, together with an optional additional message.  This would work in a similar way to the existing "Notify Reviewer" button for use by an Uploader.

**Comment by alisonrclarke** [comment]
I think throttling the emails sent might be a better solution from a user's point of view. If we rely on the reviewer clicking a button, the emails may just never get sent (especially as this will be a change in behaviour).

It looks like it should be possible using a delay in celery together with a Redis cache item to keep track of whether a job is already queued, as per [this StackOverflow answer](https://stackoverflow.com/a/34290708/15767197). I guess we could combine this with a 'notify uploader' button  if we think that would be helpful?

**Comment by GraemeWatt** [comment]
I'm not sure about the idea of delaying the Celery tasks.  I like the GitHub reviewing mechanism where code comments can be added by clicking either "Add single comment" (send notification immediately) or "Start a review" (add multiple comments before submitting the review).  Similarly, we could have two buttons on the review widget instead of the current "Send Feedback".  The first one, named something like "Submit (with email)", would reproduce the existing behaviour.  The second one, named something like "Submit (no email)", would add the review comment, but not send an email notification.  The new button "Notify Uploader" would send an email to the Uploader with the review status of each table and associated comments, together with an optional additional message.  Currently there is no way for a Reviewer to add comments relevant to a whole submission and not just a particular table.  The review widget should add some explanatory text like "Click Notify Uploader to email review status and comments of all tables.".

Actually, instead of "Notify Uploader" maybe "Notify Participants" might be better, which would be shown also for the Uploader.  The Uploader might also want to add comments to tables in a batch mode, but send them by email in one go.  Then the "Submit (with email)" and "Submit (no email)" buttons would be shown also for the Uploader.  The "Notify Reviewer" button could be removed in favour of "Notify Participants".  When clicking this button, the inclusion of the review status of each table and associated comments in the notification email should be optional (default not to include it).

**Comment by alisonrclarke** [comment]
Couple of questions about 'Notify Participants':

1. Who should it notify? (I presume we should exclude the current user from any of the suggestions below.)
   1. Only primary uploaders/reviewers?
   2. All uploaders/reviewers?
   3. All participants including coordinator?
2. Currently there is a 'reviewers_notified' flag in the DB for hepsubmission which determines whether the 'Notify Reviewer' button is displayed. Would it make sense to keep this, and use it to determine whether to say "New Data Upload" or not in the email? Or just to get rid of it and always make the email generic?

**Comment by GraemeWatt** [comment]
1.  Notify all primary Uploaders/Reviewers including the current user, since it's useful for them to see the email that was sent.  Exclude the Coordinator who does not usually participate in the review process.  Maybe a button labelled `Notify Reviewer/Uploader` would be clearer than `Notify Participants`.
2. Yes, maybe better to keep the `reviewers_notified` flag and use it to determine if a new upload has been made, so that the notification email can contain this information.

**Comment by alisonrclarke** [comment]
Just to check on the button name: if we have it as "Notify Reviewer" for uploaders and vice versa, is that not misleading as it also emails uploaders? Or should it say "Notify Reviewers/Uploaders" (which won't fit on a single line of text)?

**Comment by GraemeWatt** [comment]
Yes, I meant to use the same button `Notify Reviewer/Uploader` for both uploaders and reviewers.  But I see your point that this text is too long:
<img width="177" alt="Screenshot 2021-06-15 at 15 45 50" src="https://user-images.githubusercontent.com/11544204/122074350-0cc54780-cdf1-11eb-9e4f-10139a00ffb0.png">
It could maybe be made to fit by shifting the bell icon further to the left.  But it's probably easier just to instead write `Notify Participants`, since elsewhere in the HEPData code (e.g. the `SubmissionParticipant` object), the submission participants are only the Uploaders and Reviewers, but not the Coordinator.
