### ISSUE TITLE
plots: how to handle plots with 3 independent variables?

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#97]
@GraemeWatt, @cranmer, @lukasheinrich ? What is the convention. e.g. http://hepdata.cedar.ac.uk/view/ins1377585

**Comment by cranmer** [comment]
I don't think we have much of a convention for displaying these.

3 options:

Taking 2-d slices is an option (eg. holding 3rd coordinate fixed).

If the meaning of the dependent variable is a probability, then it makes sense to integrate over the 3rd coordinate and show a 2-d histogram of the result.

If the meaning of the dependent variable is a likelihood, then it makes sense to make a 2-d plot where the 3rd component is optimized (eg. minimize/maximize the dependent variable wrt. the 3r-d component). This is called "profiling".

**Comment by eamonnmag** [comment]
Thanks @cranmer. As an initial solution I'll give the option to select the axis.

**Comment by GraemeWatt** [comment]
I'm not sure it is so important to support plots with 3 independent variables initially, given that such cases very rarely occur.

In this particular record, Tables 1 and 2 are poorly formatted (by ATLAS), since the dependent variables are not being measured as a function of the three independent variables (`M`, `PT` and `Y`).  It would be better to give these cuts as qualifiers, leaving a table with only one row and two columns (`e+ e-` and `mu+ mu-`).  We usually take the single independent variable in cases like this to be `SQRT(S)`.  But in fact that's rather artificial and it would be better to also give `SQRT(S)` as a qualifier, leaving *zero* independent variables.  This treatment would be more appropriate for single-number measurements rather than differential distributions.  Would you be able to modify the code to support tables with *zero* independent variables?

**Comment by eamonnmag** [comment]
:octocat: (that's to replace my shocked face :D what would I have for X and Y?

**Comment by GraemeWatt** [comment]
For visualisation, you could create an artificial X axis (say, from 0 to 1) and just plot the data point in the middle (say, at 0.5), leaving the X axis unlabelled (and with no tick marks).  Or if it's complicated to do that, just omit the plot, since plots with only one data point are not so useful anyway.

**Comment by eamonnmag** [comment]
Do you have an example of such a record @GraemeWatt?

**Comment by GraemeWatt** [comment]
Tables 1 and 2 of the canonical [sample record](http://hepdata.cedar.ac.uk/view/ins1203852) would be better formatted with *zero* independent variables, moving `SQRT(S)` to be a qualifier rather than the single independent variable.

**Comment by GraemeWatt** [comment]
http://hepdata.cedar.ac.uk/view/ins1343509 is a good example with three independent variables.  Currently there are no tables, just an attached text file, because there were too many rows for the old HepData to handle.  I can try to prepare the YAML format from the text file, since it should be handled easily by the new HEPData.
